package com.xhr.courier.model;

import java.util.Date;

public class ContractContent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_content.id
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_content.content
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_content.create_time
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_content.contract_id
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    private Integer contractId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_content.send_user_id
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    private Integer sendUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_contract_content.to_user_id
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    private Integer toUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_content.id
     *
     * @return the value of t_contract_content.id
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_content.id
     *
     * @param id the value for t_contract_content.id
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_content.content
     *
     * @return the value of t_contract_content.content
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_content.content
     *
     * @param content the value for t_contract_content.content
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_content.create_time
     *
     * @return the value of t_contract_content.create_time
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_content.create_time
     *
     * @param createTime the value for t_contract_content.create_time
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_content.contract_id
     *
     * @return the value of t_contract_content.contract_id
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    public Integer getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_content.contract_id
     *
     * @param contractId the value for t_contract_content.contract_id
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    public void setContractId(Integer contractId) {
        this.contractId = contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_content.send_user_id
     *
     * @return the value of t_contract_content.send_user_id
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    public Integer getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_content.send_user_id
     *
     * @param sendUserId the value for t_contract_content.send_user_id
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    public void setSendUserId(Integer sendUserId) {
        this.sendUserId = sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_contract_content.to_user_id
     *
     * @return the value of t_contract_content.to_user_id
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    public Integer getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_contract_content.to_user_id
     *
     * @param toUserId the value for t_contract_content.to_user_id
     *
     * @mbg.generated Sat Feb 29 15:11:04 CST 2020
     */
    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }
}