package com.xhr.courier.model;

import java.util.Date;

public class CourierOrder {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_courier_order.id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_courier_order.user_id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	private Integer userId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_courier_order.address_id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	private String addressId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_courier_order.pickup_code
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	private String pickupCode;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_courier_order.courier
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	private String courier;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_courier_order.order_id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	private String orderId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_courier_order.remark
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	private String remark;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_courier_order.create_time
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_courier_order.cabinet_time
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	private Date cabinetTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_courier_order.status
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	private String status;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_courier_order.order_user_id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	private Integer orderUserId;
	private String isBig;
	private String phone;
	private String address;
	private String payStatus;
	private String price;
	private Date acceptTime;

	public Date getAcceptTime() {
		return acceptTime;
	}

	public void setAcceptTime(Date acceptTime) {
		this.acceptTime = acceptTime;
	}

	public String getPayStatus() {
		return payStatus;
	}

	public void setPayStatus(String payStatus) {
		this.payStatus = payStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_courier_order.id
	 *
	 * @return the value of t_courier_order.id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_courier_order.id
	 *
	 * @param id
	 *            the value for t_courier_order.id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_courier_order.user_id
	 *
	 * @return the value of t_courier_order.user_id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_courier_order.user_id
	 *
	 * @param userId
	 *            the value for t_courier_order.user_id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_courier_order.address_id
	 *
	 * @return the value of t_courier_order.address_id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public String getAddressId() {
		return addressId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_courier_order.address_id
	 *
	 * @param addressId
	 *            the value for t_courier_order.address_id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public void setAddressId(String addressId) {
		this.addressId = addressId == null ? null : addressId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_courier_order.pickup_code
	 *
	 * @return the value of t_courier_order.pickup_code
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public String getPickupCode() {
		return pickupCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_courier_order.pickup_code
	 *
	 * @param pickupCode
	 *            the value for t_courier_order.pickup_code
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public void setPickupCode(String pickupCode) {
		this.pickupCode = pickupCode == null ? null : pickupCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_courier_order.courier
	 *
	 * @return the value of t_courier_order.courier
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public String getCourier() {
		return courier;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_courier_order.courier
	 *
	 * @param courier
	 *            the value for t_courier_order.courier
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public void setCourier(String courier) {
		this.courier = courier == null ? null : courier.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_courier_order.order_id
	 *
	 * @return the value of t_courier_order.order_id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_courier_order.order_id
	 *
	 * @param orderId
	 *            the value for t_courier_order.order_id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_courier_order.remark
	 *
	 * @return the value of t_courier_order.remark
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_courier_order.remark
	 *
	 * @param remark
	 *            the value for t_courier_order.remark
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_courier_order.create_time
	 *
	 * @return the value of t_courier_order.create_time
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_courier_order.create_time
	 *
	 * @param createTime
	 *            the value for t_courier_order.create_time
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_courier_order.cabinet_time
	 *
	 * @return the value of t_courier_order.cabinet_time
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public Date getCabinetTime() {
		return cabinetTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_courier_order.cabinet_time
	 *
	 * @param cabinetTime
	 *            the value for t_courier_order.cabinet_time
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public void setCabinetTime(Date cabinetTime) {
		this.cabinetTime = cabinetTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_courier_order.status
	 *
	 * @return the value of t_courier_order.status
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_courier_order.status
	 *
	 * @param status
	 *            the value for t_courier_order.status
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_courier_order.order_user_id
	 *
	 * @return the value of t_courier_order.order_user_id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public Integer getOrderUserId() {
		return orderUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_courier_order.order_user_id
	 *
	 * @param orderUserId
	 *            the value for t_courier_order.order_user_id
	 *
	 * @mbg.generated Sun Jan 26 18:17:36 CST 2020
	 */
	public void setOrderUserId(Integer orderUserId) {
		this.orderUserId = orderUserId;
	}

	public String getIsBig() {
		return isBig;
	}

	public void setIsBig(String isBig) {
		this.isBig = isBig;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

}