package com.xhr.courier.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.login_name
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.avatar
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_type
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.create_time
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email_code
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    private String emailCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.specialty
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    private String specialty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.class_name
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.student_id_card
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    private String studentIdCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.auth
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    private String auth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param userName the value for t_user.user_name
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.login_name
     *
     * @return the value of t_user.login_name
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.login_name
     *
     * @param loginName the value for t_user.login_name
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.avatar
     *
     * @return the value of t_user.avatar
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.avatar
     *
     * @param avatar the value for t_user.avatar
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_type
     *
     * @return the value of t_user.user_type
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_type
     *
     * @param userType the value for t_user.user_type
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.create_time
     *
     * @return the value of t_user.create_time
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.create_time
     *
     * @param createTime the value for t_user.create_time
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.phone
     *
     * @return the value of t_user.phone
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.phone
     *
     * @param phone the value for t_user.phone
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email_code
     *
     * @return the value of t_user.email_code
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public String getEmailCode() {
        return emailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email_code
     *
     * @param emailCode the value for t_user.email_code
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public void setEmailCode(String emailCode) {
        this.emailCode = emailCode == null ? null : emailCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.specialty
     *
     * @return the value of t_user.specialty
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.specialty
     *
     * @param specialty the value for t_user.specialty
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public void setSpecialty(String specialty) {
        this.specialty = specialty == null ? null : specialty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.class_name
     *
     * @return the value of t_user.class_name
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.class_name
     *
     * @param className the value for t_user.class_name
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.student_id_card
     *
     * @return the value of t_user.student_id_card
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public String getStudentIdCard() {
        return studentIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.student_id_card
     *
     * @param studentIdCard the value for t_user.student_id_card
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public void setStudentIdCard(String studentIdCard) {
        this.studentIdCard = studentIdCard == null ? null : studentIdCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.auth
     *
     * @return the value of t_user.auth
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public String getAuth() {
        return auth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.auth
     *
     * @param auth the value for t_user.auth
     *
     * @mbg.generated Fri Mar 06 20:06:44 CST 2020
     */
    public void setAuth(String auth) {
        this.auth = auth == null ? null : auth.trim();
    }
}