package com.xhr.courier.model;

import java.util.Date;

public class User {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.id
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.user_name
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	private String userName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.login_name
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	private String loginName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.password
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	private String password;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.avatar
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	private String avatar;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.user_type
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	private String userType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.create_time
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	private Date createTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.phone
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	private String phone;

	private String email;

	private String emailCode;

	public String getEmailCode() {
		return emailCode;
	}

	public void setEmailCode(String emailCode) {
		this.emailCode = emailCode;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.id
	 *
	 * @return the value of t_user.id
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.id
	 *
	 * @param id
	 *            the value for t_user.id
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.user_name
	 *
	 * @return the value of t_user.user_name
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.user_name
	 *
	 * @param userName
	 *            the value for t_user.user_name
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.login_name
	 *
	 * @return the value of t_user.login_name
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public String getLoginName() {
		return loginName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.login_name
	 *
	 * @param loginName
	 *            the value for t_user.login_name
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public void setLoginName(String loginName) {
		this.loginName = loginName == null ? null : loginName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.password
	 *
	 * @return the value of t_user.password
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.password
	 *
	 * @param password
	 *            the value for t_user.password
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.avatar
	 *
	 * @return the value of t_user.avatar
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public String getAvatar() {
		return avatar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.avatar
	 *
	 * @param avatar
	 *            the value for t_user.avatar
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public void setAvatar(String avatar) {
		this.avatar = avatar == null ? null : avatar.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.user_type
	 *
	 * @return the value of t_user.user_type
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public String getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.user_type
	 *
	 * @param userType
	 *            the value for t_user.user_type
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public void setUserType(String userType) {
		this.userType = userType == null ? null : userType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.create_time
	 *
	 * @return the value of t_user.create_time
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.create_time
	 *
	 * @param createTime
	 *            the value for t_user.create_time
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.phone
	 *
	 * @return the value of t_user.phone
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.phone
	 *
	 * @param phone
	 *            the value for t_user.phone
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}
}