package com.xhr.courier.dao;

import com.xhr.courier.model.ContractContent;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ContractContentMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_contract_content
	 *
	 * @mbg.generated Sat Feb 29 15:11:04 CST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_contract_content
	 *
	 * @mbg.generated Sat Feb 29 15:11:04 CST 2020
	 */
	int insert(ContractContent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_contract_content
	 *
	 * @mbg.generated Sat Feb 29 15:11:04 CST 2020
	 */
	ContractContent selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_contract_content
	 *
	 * @mbg.generated Sat Feb 29 15:11:04 CST 2020
	 */
	List<ContractContent> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_contract_content
	 *
	 * @mbg.generated Sat Feb 29 15:11:04 CST 2020
	 */
	int updateByPrimaryKey(ContractContent record);

	List<Map<String, Object>> findByContractIdContract(int contractId);
	List<Map<String, Object>> findByContractIdContractInfo(int contractId);

	List<Map<String, Object>> findByUserIdOrToUserIdContractInfo(Map<String, Object> map);
}