package com.xhr.courier.dao;

import com.xhr.courier.model.CourierOrder;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface CourierOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courier_order
     *
     * @mbg.generated Sun Jan 26 18:17:36 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courier_order
     *
     * @mbg.generated Sun Jan 26 18:17:36 CST 2020
     */
    int insert(CourierOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courier_order
     *
     * @mbg.generated Sun Jan 26 18:17:36 CST 2020
     */
    CourierOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courier_order
     *
     * @mbg.generated Sun Jan 26 18:17:36 CST 2020
     */
    List<CourierOrder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_courier_order
     *
     * @mbg.generated Sun Jan 26 18:17:36 CST 2020
     */
    int updateByPrimaryKey(CourierOrder record);
    
    int update(Map<String, Object> map);
    
    List<Map<String, Object>> findList(Map<String, Object> map);

	List<Map<String, Object>> findListIndex(Map<String, Object> map);
}