package com.xhr.courier.dao;

import com.xhr.courier.model.User;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	User selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	List<User> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_user
	 *
	 * @mbg.generated Sun Jan 26 14:57:26 CST 2020
	 */
	int updateByPrimaryKey(User record);

	List<User> findList(Map<String, Object> map);
	
	int update(Map<String, Object> map);
}